### PR TITLE
Add favicon.ico to the Sphinx (i.e. readthedocs) documentation

### PR DESCRIPTION
**Pull request by moy**
The scaled-down version is far less readable than the full-size version. It's probably possible to make a much better favicon with time and skills, but let's start with something simple (to merge, or to improve).

### CODE REVIEW

**Comment by moy** [comment]
I changed the target branch of readthedocs temporarily to this PR to see it live. It's there until the next build (i.e. next push to master): https://mechanicalsoup.readthedocs.io/en/latest/

**Comment by moy** [comment]
Unfortunately I don't seem to be able to do much better in reasonable time. The best I could come up is:

favicon

Still not readable at 16x16, but perhaps less ugly:

ff

I'm fine with not merging this, but it may make sense to merge and improve later. No strong preference.

**Comment by hemberger** [comment]
In the interest of removing stale branches from this repository (i.e. `test-readthedocs`), would you mind if I close this PR? If you'd like me to do something else to preserve your desire for a customized favicon, I'm more than happy to do it. Thanks!

**Comment by moy** [comment]
OK for closing this PR & branch.

**Pull request closed without merging**
