### PR TITLE
added ability to not edit disabled

### PR DESCRIPTION
**Pull request by rationa-kunal**
Added dev_op boolean variable to Form
if dev_op is True then you can edit disabled inputs
else dev_op is False then you cant edit disabled inputs

### CODE REVIEW

**Comment by moy** [comment]
We have automatic testing, and as you see there are issues to fix in your code (at least flake8 formatting issues). This would also require documentation and more tests (we have a strict 100% coverage policy).

But as I said in #248, I don't think this is the right approach. If you think it is, then please rewrite the commit message to explain 1) the issue you are trying to solve and 2) why you think your modifications are the best way to fix this issue.

**Comment by moy** [comment]
As I wrote in https://github.com/MechanicalSoup/MechanicalSoup/issues/248#issuecomment-443687132, I don't think edition of disabled fields is the problem. The first thing to fix is the form _submission_.

Also, the Travis build fails, we can't merge a PR with test failures, sorry.

**Comment by rationa-kunal** [comment]
How can I add test case for this issue ?
There is no disabled form field in httpbin !

**Comment by moy** [comment]
I believe 685eb6e1396008a0b3881bea5bcc6b7119f61642 fixed the main problem with disabled fields, so let's close this.

**Pull request closed without merging**
