### PR TITLE
change browser.page by browser.get_current_page()

### PR DESCRIPTION
**Pull request by jbarotin**
browser.page is not working

### CODE REVIEW

**Comment by moy** [comment]
`browser.page` is working, but it's a recent feature, unreleased for now.

@hemberger : shall we release 1.0, BTW?

**Comment by jbarotin** [comment]
As you, I tried the example with the version installed though pip (MechanicalSoup==0.12.0), and it's not working with ".page".  

After reading your documentation (because the ".page" not working), I changed to ".get_current_page()" and then get the example to work...

**Comment by moy** [comment]
By definition, 0.12 is not an unreleased version ;-)

**Comment by hemberger** [comment]
@moy I have no problem with 1.0 being released. The only question I have is whether or not we want to refer to the old methods as "deprecated" in the changelog (which may be stressful to people migrating), or if we want to refer to the new interface as a convenience that *may* one day replace the existing methods.

**Pull request closed without merging**
