### PR TITLE
Adds logo to readme and documentation

### PR DESCRIPTION
**Pull request by mkormendy**

### CODE REVIEW

**Comment by hemberger** [comment]
Thanks for your contribution! We're really excited to have such a cool logo for MechanicalSoup.

I have a few comments now that I see it in context:
1. The logo text looks a bit faded in contrast to the stark black text of the README. I'm not sure if or how that should be changed, but my eye was drawn to it. I also find it hard to read the tagline. (See image below.)
2. Now that the text isn't stylized, it looks a bit simple and out of place, especially when surrounded by similarly simple sans serif fonts. Is there a more stylized font we could use -- maybe one that looks a bit more... mechanical? :P
3. Is it necessary to have a "MechanicalSoup" header followed immediately by a logo with the name of the module? Probably yes, in case there is anyone not loading images, but it feels a bit redundant, and might be nice to remove if we could so that the logo could speak for us!

image

**Comment by mkormendy** [comment]
I see! Let me make some changes before you pull the changes in.

Here's what I propose:

- the "faded" appearance of the text is a design aesthetic, when standing against the logo, if it is pure black, it causes a visual hierarchical conflict (your eye doesn't know where to start first)
- the difficulty with reading the tagline is due to the typeface not being respected in the rendering on your computer – let me figure out how best to get the SVG to pull that in from google's open source fonts
- it's important to have the name of the project below the image for the often-found instance when the image is sourced on the internet (hot-linked or found in an image search), then the name of the project gets "packaged" with the illustration all in the one image file, so it keeps it together, and encourages people to not steal the illustration for their own project

**Comment by moy** [comment]
I've just added two commits:

* Instructions on how to edit the logo with Inkscape (I confirm that I can do at least basic editing in Inkscape, and after installing the right fonts I get the same rendering as the PNG, so if we ever need minor adjustments it's possible).
* Better integration in the generated HTML

I think it's ready for merging (we can do a bit of `rebase -i` to squash @mkormendy 's commits together while merging). @hemberger , OK for merging?

**Comment by moy** [comment]
Oops, one more tiny improvement that should address the "in case there is anyone not loading images" concern: add an `alt=` text to the README.

**Comment by hemberger** [comment]
I wanted to play with fonts a little bit first. I think I can do what I want to do by the end of Tuesday, if that's okay.

**Comment by moy** [comment]
No problem.

**Comment by hemberger** [comment]
Now I know this looks terrible, but I found a cool font that I wanted to try out before we commit to the current design -- just try not to judge it by my poor execution. ;)

I know it's a little busy, and definitely less professional, but I think it's more fun. I could go either way!

mechanical-soup-logo2

**Comment by moy** [comment]
I like the idea of the "mechanical" font, but I think the level of details is not right compared to the rest of the logo: if the logo is rendered with a small size, then one won't see what the font is about anymore. On a large size version the rest of the logo seems too flat compared to the text.

Perhaps we can keep the simple font when MechanicalSoup is displayed below the logo, but find a place to write MechanicalSoup with this fun font elsewhere?

BTW, what font is it?

**Comment by hemberger** [comment]
Agreed about the level of detail. Your plan sounds good to me!

The font is called [Steamy](https://www.1001freefonts.com/steamy.font). I'm attaching the font files here should they ever be inaccessible from the online font repositories for some reason: [steamy.zip](https://github.com/MechanicalSoup/MechanicalSoup/files/2341791/steamy.zip)

**Comment by mkormendy** [comment]
At the very least of the issues here, @moy hit's the nail on the head about missing the detail at smaller sizes.

It's hard to not get a little butt-hurt when people attempt to modify something I created, especially when I put time and effort with deliberate results.
I mean, I went to school for this for six years and I was critiqued over and over time and again, until I understood the extremely subtle differences in proportion, scale, hierarchy, balance, contrast, position, color, shape and structure (to name a few). While this took _me_ a short time to put together, it was over a decade of experience in the making and learning what works and what doesn't based on the experience of my mentors and peers who are qualified and respected in this field.
This is how all of this allows me to execute it as I have, and as quickly as I have.

That being said, design is not art. Design is extremely deliberate. Each aspect of the illustration is intentional for a reason, the shape and choice of the elements, to the scalability at different sizes. To the proportion of the weights of the lines themselves in comparison to each other. So too does the choice of typeface I chose. It's highly legible, abstracted to it's simple geometric forms, in-line with the illustration.

Simply finding a "mechanical font" and typing it out on the illustration someone else, is a bit of a slap in the face. Just imagine if I used my amateur writing skills to go over the documentation you so carefully crafted, instead rewriting 2/5ths of it with less than stellar results to your standard.

That being said, do what you want with my logo, I just know that what I produced is exemplary and appropriate for your project to the end. Have a little trust in the professionals.

**Comment by hemberger** [comment]
People fork our code all the time. They modify it according to their needs and desires.

Our intention here is not to brand MechanicalSoup, so the decision process doesn't need to be so academic. We're trying to have a little fun with it.

**Comment by mkormendy** [comment]
Quite the opposite, you're attempting to brand the project by producing some artwork for it. The back and forth dialogue in the original issue #111 talking about doing iterations, and sizing:  "organization profile picture to get a sense of what it currently looks like in some of the applications that use a small version of the icon" is a pure example of an academic process.

All I'm saying is that, while I love that you are playing around with graphic design, you have to be a little more weary about the toes you step on when you go and modify someone else's work, even if you're forking it (which really isn't the case here either, as I am contributing my work to the repo as canon).

**Comment by hemberger** [comment]
When you submitted your PR, you checked an "Allow edits from maintainers" box, and nowhere did you express your desire for exclusive rights to the design decision. Nevertheless, I had no intention of using a modified version of your design without your permission.

@moy I would prefer to table this for now. If you feel super strongly that this represents your vision, then merge it -- I defer to you as the primary contributor to the project. My recommendation is to wait and re-evaluate our options at a later time.

**Comment by mkormendy** [comment]
Why does this have to go there. Why couldn’t you have had the common courtesy to jut leave it be?

**Comment by mkormendy** [comment]
I can’t see the checkbox to not allow maintainers to modify this request.

**Comment by mkormendy** [comment]
I’m freely giving it to the project, do with it what you wish. My original intention was to contribute to the project with skills I was confident in, as thanks for creating the code which helped me with an additional project. My understanding of the nature of the project was amiss, and now that I understand the fun-nature of it, I digress and apologize for any misunderstanding. The artwork/logo is yours to do with as you wish, with further modifications or not.

**Comment by hemberger** [comment]
Thanks for your understanding, @mkormendy.

@moy: Unless I hear otherwise, I'll leave it to you to merge this, since you probably have a better idea of how you want to merge in your commits.

**Comment by moy** [comment]
Actually a single commit is sufficient I think. I squashed everything in #234. I'm closing this one in favor of it.

**Pull request closed without merging**
